### ISSUE TITLE
how to use it in python?

### ISSUE THREAD

**Issue by Little-Frog-233** [pyecharts/pyecharts-snapshot#43]
i want to use it in python to turn encharts.html into png, how can i do this?

**Comment by chfw** [comment]
I am afraid that the latest version will stay as cli tool because it uses asyncio and pypuppeteer. Please refer to snapshot-selenium or snapshot-phantomjs for programmatical usage.

I would not recommend to use older versions of this library because the next question, which version of pyecharts will work with older ones.

**Comment by Little-Frog-233** [comment]
Thank you very much






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jaska"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月27日(星期五) 晚上9:32
收件人:&nbsp;"pyecharts/pyecharts-snapshot"<pyecharts-snapshot@noreply.github.com&gt;;
抄送:&nbsp;"晓辰"<1342468180@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pyecharts/pyecharts-snapshot] how to use it in python? (#43)




Closed #43.

**Comment by chfw** [comment]
https://github.com/pyecharts/snapshot-pyppeteer

Is programmatical equivalent. Check it out!
